#!/usr/bin/env node
// The quote builder's names, and nothing else (O15).
//
//   node tools/builder-names.mjs [captureDir] [--check]
//
// Reads the Builder capture of 2026-09-09 in Market Intel (docs/discovery/solution-builder-catalog-
// 2026-09-09: catalog.json for the services, packages.md for the seven curated packages) and writes
// content/builder-names.json: the categories, every non-draft service with its category, the draft
// names listed apart so the lint can name them, and the package names. Codes, prices, billing units,
// descriptions and hours never leave the capture. The "[Confirm price]" items are marked held: their
// names may stand only as program names until the owner confirms them. The file is pinned to the
// capture by date and by the sha256 of the two files it was read from.
//
// captureDir defaults to ../3Hue-Market-Intel/docs/discovery/solution-builder-catalog-2026-09-09 next
// to this repo (or $BUILDER_CAPTURE). --check regenerates in memory and exits 1 when the committed
// file differs. The lint and the specs import offerId() so an offer's id cannot drift from its name.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const OUT = 'content/builder-names.json';
export const CAPTURE = '2026-09-09';
const REPO_DIR = '3Hue-Market-Intel/docs/discovery/solution-builder-catalog-2026-09-09';
export const DEFAULT_DIR = process.env.BUILDER_CAPTURE || path.resolve(ROOT, '..', REPO_DIR);

// An offer's id: its Builder name in lower case, "&" dropped, every other run of anything but a letter
// or digit one hyphen. "Manage Risk Register & POA&M" → manage-risk-register-poam.
export const offerId = (name) => String(name ?? '').toLowerCase().replace(/&/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
// Anything shaped like a price, a rate, an hour count or a Builder code. A name that looks like one
// would carry the thing the site must not show, so the build stops rather than write it.
const PRICEY = /[$€£]|\b\d[\d,.]*\s*(?:\/|per\s)\s*(?:h|hr|hour|mo|month|yr|year|node)\b|\b\d+\s*(?:hours?|hrs?)\b|\b[A-Z]{2,}(?:-[A-Z0-9]+){2,}\b/;

export function buildNames(dir = DEFAULT_DIR) {
  const catBuf = fs.readFileSync(path.join(dir, 'catalog.json'));
  const pkgBuf = fs.readFileSync(path.join(dir, 'packages.md'));
  const cat = JSON.parse(catBuf);
  if (cat.observedAt !== CAPTURE) throw new Error(`catalog.json was observed ${cat.observedAt}; this file is pinned to the ${CAPTURE} capture`);
  const all = Array.isArray(cat.services) ? cat.services : [];
  const isDraft = (s) => s.catalogStatus === 'draft';
  const isHeld = (s) => s.priceStatus === 'confirm' || /\[Confirm price\]/i.test(s.description || '');
  const live = all.filter((s) => !isDraft(s)), drafts = all.filter(isDraft);
  const categories = [...new Set(live.map((s) => s.category))];
  const services = live.map((s) => ({ name: s.name, category: s.category, draft: false, ...(isHeld(s) ? { held: true } : {}) }));
  // packages.md: the first column of the table, on rows whose second column is a service count.
  const packages = [...String(pkgBuf).matchAll(/^\|\s*([^|]+?)\s*\|\s*\d+\s*\|/gm)].map((x) => ({ name: x[1] }));
  const out = {
    capture: CAPTURE,
    source: `${REPO_DIR}/catalog.json sha256:${sha256(catBuf)}`,
    packagesSource: `${REPO_DIR}/packages.md sha256:${sha256(pkgBuf)}`,
    note: 'Names only, generated by tools/builder-names.mjs from the Builder capture: no codes, prices, billing units, descriptions or hours. held = the Builder shows [Confirm price]; such a name may stand only as a program name. draft = on the Builder\'s draft catalog; never on the site.',
    categories,
    services,
    draft: { categories: [...new Set(drafts.map((s) => s.category))].filter((c) => !categories.includes(c)), services: drafts.map((s) => s.name) },
    packages,
  };
  // Refuse a capture this file cannot represent: duplicate or colliding ids, a price-shaped name,
  // a package count that is not the seven the Builder showed.
  const names = [...services.map((s) => s.name), ...packages.map((p) => p.name), ...out.draft.services];
  const ids = new Map();
  for (const n of names) {
    if (PRICEY.test(n)) throw new Error(`price- or code-shaped name in the capture: ${n}`);
    const id = offerId(n);
    if (ids.has(id)) throw new Error(`"${n}" and "${ids.get(id)}" share the id ${id}`);
    ids.set(id, n);
  }
  if (packages.length !== 7) throw new Error(`expected the 7 curated packages in packages.md, found ${packages.length}`);
  return out;
}

// One entry per line inside the lists, so a Builder change reads as a one-line diff.
export function formatNames(o) {
  const block = (arr, ind) => (arr.length ? `[\n${arr.map((x) => `${ind}  ${JSON.stringify(x)}`).join(',\n')}\n${ind}]` : '[]');
  const lines = Object.entries(o).map(([k, v]) => {
    if (Array.isArray(v)) return `  ${JSON.stringify(k)}: ${block(v, '  ')}`;
    if (v && typeof v === 'object') return `  ${JSON.stringify(k)}: {\n${Object.entries(v).map(([k2, v2]) => `    ${JSON.stringify(k2)}: ${block(v2, '    ')}`).join(',\n')}\n  }`;
    return `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`;
  });
  return `{\n${lines.join(',\n')}\n}\n`;
}

function main(argv) {
  const check = argv.includes('--check');
  const dir = argv.find((a) => !a.startsWith('--')) || DEFAULT_DIR;
  if (!fs.existsSync(path.join(dir, 'catalog.json'))) { console.error(`no catalog.json in ${dir}; pass the capture folder (Market Intel ${REPO_DIR})`); process.exit(2); }
  const text = formatNames(buildNames(dir));
  const file = path.join(ROOT, OUT);
  if (check) {
    const same = fs.existsSync(file) && fs.readFileSync(file, 'utf8') === text;
    console.log(same ? `${OUT} matches the capture` : `${OUT} differs from the capture; run node tools/builder-names.mjs`);
    process.exit(same ? 0 : 1);
  }
  fs.writeFileSync(file, text);
  const o = JSON.parse(text);
  console.log(`${OUT}: ${o.categories.length} categories, ${o.services.length} services (${o.services.filter((s) => s.held).length} held), ${o.packages.length} packages; ${o.draft.services.length} draft names kept apart`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main(process.argv.slice(2));
