// The door copy sheet: every buyer-facing sentence in the three door panels and the path panel, as
// the manifest holds it, with the source and status of each figure.
//
//   node tools/door-sheet.mjs [file]     write the sheet (default docs/copy-sheets.md)
//   node tools/door-sheet.mjs --check    exit 1 if the sheet on disk is not what this would write
//
// Written because the sheet said "Generated from content/experience.json" for months while nothing
// generated it: by 2026-09-14 it still showed the retired triggers, a service family no door
// carries, and "Snapshot" as the first step of How it runs, which is `arc[0]` and had since become
// "Scope". A sheet the owner signs should not be able to drift without anyone noticing.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const m = read('content/experience.json');

const argv = process.argv.slice(2);
const check = argv.includes('--check');
const OUT = argv.find((a) => !a.startsWith('--')) || 'docs/copy-sheets.md';

// A sourced field prints its text, then its provenance and status on the line under it. `status` is
// what the copy gate reads, so it is never dropped, even when it is only "proposed".
// Proof entries cite a `basis` rather than a `source`; everything else carries `source`.
const sourced = (o, label = 'Source') => {
  const from = o && (o.source ?? o.basis);
  return from ? `*${label}: ${from}${o.status ? ` (${o.status})` : ''}*` : null;
};
const textOf = (v) => (typeof v === 'string' ? v : v && typeof v.text === 'string' ? v.text : null);

const L = [];
const push = (...xs) => L.push(...xs);

push('# Door copy sheets', '');
push(`Every buyer-facing sentence in the three door panels, with the source of each figure. Generated by \`node tools/door-sheet.mjs\` from \`content/experience.json\`; regenerate after any manifest change and do not edit this file by hand.`, '');

for (const d of m.doors) {
  push(`## ${d.title}: ${d.promise}`, '');
  const head = [];
  if (d.icp) head.push(`**Buyer label:** ${d.icp}`);
  if (d.tension) head.push(`**Lede:** ${d.tension}`);
  if (d.audience) head.push(`**Audience:** ${d.audience}`);
  // Two trailing spaces are a markdown line break: each field sits on its own line in one block.
  push(head.map((x, i) => (i === head.length - 1 ? x : `${x}  `)).join('\n'), '');

  push('### What creates urgency', '');
  if (d.opening) {
    push(`> ${d.opening.text}  `, `> — ${d.opening.source}${d.opening.status ? ` (${d.opening.status})` : ''}`, '');
  }
  for (const t of d.triggers || []) push(`- ${t}`);
  if ((d.triggers || []).length) push('');
  if (d.stat) push(`${d.stat.text}  `, sourced(d.stat), '');

  push('### The gap to close', '');
  if (d.gap) push(d.gap, '');
  if (d.statSecondary) push(`${d.statSecondary.text}  `, sourced(d.statSecondary), '');

  push(`### ${m.strings.services}`, '');
  // Builder category names exactly as the quote builder writes them (O15), not a paraphrase.
  for (const f of d.serviceFamilies || []) push(`- **${f.name}**: ${(f.examples || []).join(' · ')}`);
  push('');

  if ((d.proof || []).length) {
    push('### Proof on record', '');
    for (const p of d.proof) push(`${p.text}  `, sourced(p, 'Basis'), '');
  }

  push('### How it runs', '');
  // The three step labels are the manifest's own arc, so renaming a step renames it here too.
  const steps = ['start', 'build', 'operate'];
  steps.forEach((k, i) => { if (d.program?.[k]) push(`${i + 1}. **${m.arc[i]}** ${d.program[k]}`); });
  push('');
  const psrc = sourced(d.program);
  if (psrc) push(`${psrc}  `);
  push(`Pillars: ${(m.pillars || []).join(' · ')}`, '');

  push('### Shared maturity route', '');
  const inPath = new Set(d.maturityEmphasis || []);
  push(m.stages.map((s) => `${s.name}${inPath.has(s.id) ? ' (in this path)' : ''}`).join(' → '), '');

  push('### Next decision', '');
  const decision = textOf(d.decision);
  if (decision) push(decision, '');
  const dsrc = sourced(d.decision);
  if (dsrc) push(dsrc, '');
}

push('## The maturity path', '');
if (m.path?.whereToStart) {
  push(`**Where to start:** ${m.path.whereToStart.lead}  `, sourced(m.path.whereToStart), '');
}

push('## Kiosk', '');
const kiosk = [m.kiosk?.header, ...(m.kiosk?.lines || []).map((l) => l.label), m.kiosk?.tag].filter(Boolean);
push(`${kiosk.join(' · ')} (counts derived from this manifest)`, '');

const out = L.filter((x) => x !== null).join('\n');

if (check) {
  const have = fs.existsSync(path.join(ROOT, OUT)) ? fs.readFileSync(path.join(ROOT, OUT), 'utf8').replace(/\r\n/g, '\n') : '';
  if (have.trimEnd() === out.trimEnd()) { console.log(`${OUT} is current`); process.exit(0); }
  console.error(`${OUT} is stale: run node tools/door-sheet.mjs`);
  process.exit(1);
}

fs.writeFileSync(path.join(ROOT, OUT), `${out}\n`);
console.log(`wrote ${OUT}: ${m.doors.length} doors, ${m.doors.reduce((n, d) => n + (d.serviceFamilies || []).length, 0)} service families`);
